# DockerFile
FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENV MODEL_DIR=/app/models
EXPOSE 8080

ENTRYPOINT ["/entrypoint.sh"]
